import { readFileSync, writeFileSync } from 'node:fs'
import { basename, resolve } from 'node:path'
import { Glob } from 'bun'
import { RenderError } from './errors'
import { extractFrontmatter } from './frontmatter'
import { type ParamSpec, parseParamSpecs } from './params'

export interface TypegenOptions {
  /** Directory to resolve glob patterns from. @default process.cwd() */
  cwd?: string
  /** When false, declarations are returned but not written to disk. @default true */
  write?: boolean
}

export interface TypegenEntry {
  /** Absolute path of the markdown file. */
  file: string
  /** Absolute path of the generated declaration file (`x.d.md.ts` for `x.md`). */
  declarationFile: string
  /** Declaration file contents. */
  contents: string
}

const MARKDOWN_EXTENSION = /\.(md|markdown)$/i
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

/**
 * Walk glob patterns of markdown files and emit a sibling `.d.md.ts` declaration
 * for each (like typed-css-modules), typing the module's default export from the
 * file's frontmatter param declarations. Requires `"allowArbitraryExtensions":
 * true` in the consumer's tsconfig so TypeScript picks the declarations up.
 */
export function typegen(patterns: string | string[], options: TypegenOptions = {}): TypegenEntry[] {
  const cwd = resolve(options.cwd ?? process.cwd())
  const files = new Set<string>()
  for (const pattern of Array.isArray(patterns) ? patterns : [patterns]) {
    for (const file of new Glob(pattern).scanSync({ cwd, absolute: true, onlyFiles: true })) {
      if (MARKDOWN_EXTENSION.test(file) && !/(^|\/)node_modules\//.test(file)) {
        files.add(file)
      }
    }
  }

  const entries: TypegenEntry[] = []
  for (const file of [...files].sort()) {
    const contents = generateDeclaration(file)
    const declarationFile = file.replace(MARKDOWN_EXTENSION, (_match, ext) => `.d.${ext}.ts`)
    if (options.write !== false) {
      writeFileSync(declarationFile, contents, 'utf-8')
    }
    entries.push({ file, declarationFile, contents })
  }
  return entries
}

/** Generate the declaration file contents for a single markdown file. */
export function generateDeclaration(filePath: string): string {
  const path = resolve(filePath)
  const source = readFileSync(path, 'utf-8')
  let specs: ParamSpec[] = []
  try {
    const document = extractFrontmatter(source)
    if (document.hasFrontmatter) {
      specs = parseParamSpecs(document.frontmatter, path)
    }
  } catch (error) {
    if (error instanceof RenderError) throw error
    throw new RenderError(
      'invalid-declaration',
      path,
      `failed to parse frontmatter: ${error instanceof Error ? error.message : String(error)}`,
    )
  }
  return renderDeclaration(basename(path), specs)
}

function renderDeclaration(fileName: string, specs: ParamSpec[]): string {
  const lines: string[] = [
    `// Generated by @markdown-di/bun typegen from ${fileName} — do not edit.`,
    '',
  ]

  let renderSignature: string
  if (specs.length === 0) {
    renderSignature = 'declare function render(): string'
  } else {
    const interfaceName = paramsInterfaceName(fileName)
    lines.push(`export interface ${interfaceName} {`)
    for (const spec of specs) {
      lines.push(`  ${propertyName(spec.name)}${spec.required ? '' : '?'}: ${spec.type}`)
    }
    lines.push('}', '')
    const optional = specs.every((spec) => !spec.required) ? '?' : ''
    renderSignature = `declare function render(params${optional}: ${interfaceName}): string`
  }

  lines.push(
    renderSignature,
    'export default render',
    '',
    'export declare const frontmatter: Record<string, unknown>',
    'export declare const source: string',
    '',
  )
  return lines.join('\n')
}

function paramsInterfaceName(fileName: string): string {
  const stem = fileName.replace(MARKDOWN_EXTENSION, '')
  const pascal = stem
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('')
  const safe = /^[0-9]/.test(pascal) ? `_${pascal}` : pascal || 'Markdown'
  return `${safe}Params`
}

function propertyName(name: string): string {
  return IDENTIFIER.test(name) ? name : JSON.stringify(name)
}
